Homepage
Godfrey-Alimony/Hello-World pull request #1
Opened 2022-04-19 23:00 UTC by Godfrey-Alimony

Added image folder of the webpage.
Added HTML File of the project.
Added Css File of the project.
Added MIT File of the project.

2022-04-19 23:30 UTC, AnselemOdims requested changes
### Hi @Godfrey-Alimony , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] There should be a `.gitignore` file, that includes `node_modules` and `test.md`. Kindly make sure you include it as it will help ensure that unnecessary files or dependencies are not pushed to remote.
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-04-19 23:30 UTC, AnselemOdims commented on README.md
> +internet
- [ ] Kindly fill up these empty sections or remove them completely. This will make the README more professional.

2022-04-20 05:56 UTC, Godfrey-Alimony commented
Added README File of the Project.
Added comment on the HTML and CSS File.
Added .gitignore file and node_module,test.md Under it.

2022-04-20 06:15 UTC, roshan-bajgain requested changes
Hi @Godfrey-Alimony , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

### To highlight :tada: :champagne: 
- No linter error :heavy_check_mark:
- GitHub flow is followed :+1:


## Required Changes ♻️
- [ ]  Kindly create a .gitignore file, that includes node_modules and test.md So that unnecessary dependencies are not pushed to the remote. Kindly implement said by the previous reviewer.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-20 06:35 UTC, Godfrey-Alimony commented
Dear sir/madam,
How are you? please check i have created gitignore file which include
node_modules and test.md.
Thanks

On Wed, Apr 20, 2022 at 9:15 AM Roshan Bajgain ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Godfrey-Alimony <https://github.com/Godfrey-Alimony> ,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> To highlight 🎉 🍾
>
>    - No linter error ✔️
>    - GitHub flow is followed 👍
>
> Required Changes ♻️
>
>    - Kindly create a .gitignore file, that includes node_modules and
>    test.md So that unnecessary dependencies are not pushed to the remote.
>    Kindly implement said by the previous reviewer.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Godfrey-Alimony/Hello-World/pull/1#pullrequestreview-946634992>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARA7M6ZGBG4DPWD6U6SSM2TVF6OHJANCNFSM5T2I2U5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-20 06:42 UTC, roshan-bajgain commented
@Godfrey-Alimony If you are done then I suggest you submit the same pull request on your dashboard.

2022-04-20 06:46 UTC, Godfrey-Alimony commented
Yes, I have submitted it.
Thanks
[image: Screenshot from 2022-04-20 09-45-09.png]

On Wed, Apr 20, 2022 at 9:42 AM Roshan Bajgain ***@***.***>
wrote:

> @Godfrey-Alimony <https://github.com/Godfrey-Alimony> If you are done
> then I suggest you submit the same pull request on your dashboard.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Godfrey-Alimony/Hello-World/pull/1#issuecomment-1103527676>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARA7M63WGDTEQZ7EEWW7KH3VF6RN3ANCNFSM5T2I2U5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-04-20 08:02 UTC, Godfrey-Alimony commented
https://github.com/Godfrey-Alimony/Hello-World/pull/1

2022-04-20 08:19 UTC, Godfrey-Alimony commented
Thank you so much sir.

2022-04-20 08:19 UTC, merged

2022-04-22 05:10 UTC, Godfrey-Alimony commented
Dear sir;
How are you? well i have done all that I could please approve my project so
that  I start the next one.Thanks

On Wed, Apr 20, 2022 at 9:15 AM Roshan Bajgain ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @Godfrey-Alimony <https://github.com/Godfrey-Alimony> ,
>
> Good job so far!
> There are some issues that you still need to work on to go to the next
> project but you are almost there!
> To highlight 🎉 🍾
>
>    - No linter error ✔️
>    - GitHub flow is followed 👍
>
> Required Changes ♻️
>
>    - Kindly create a .gitignore file, that includes node_modules and
>    test.md So that unnecessary dependencies are not pushed to the remote.
>    Kindly implement said by the previous reviewer.
>
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix is not crucial enough to stop
> the approval of this PR. However, I strongly recommend you to take them
> into account as they can make your code better.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Godfrey-Alimony/Hello-World/pull/1#pullrequestreview-946634992>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARA7M6ZGBG4DPWD6U6SSM2TVF6OHJANCNFSM5T2I2U5A>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>